name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:
  push:
    # Ensure test job passes before pushing image.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Base Image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: elrichindy/aods_base
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: base_image
          tags: "latest,py3.7,base"
      - name: Publish AODS Images
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: elrichindy/aods
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,py3.7"
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2.1.0
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERHUB_REPOSITORY: elrichindy/aods
          # This can be remove if default of README.md in base dir, leaving for reference
          README_FILEPATH: ./README.md
