name: DockerPush

on:
  push:
    paths-ignore:
      - '.github/workflows/dockerreadme.yml'
      - 'README.md'
    branches:
      - master
    tags:
      - v*
  pull_request:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Base Image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: elrichindy/aods_base
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: base_image
          tags: "latest,py3.7,base"
      - name: Publish AODS Images
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: elrichindy/aods
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,py3.7"